spring:
  profiles: dev
  application:
    name: carwash-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/carwashes
      repositories:
        enabled: true

server:
  port: 8085

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: INFO

springdoc:
  info:
    title: API для клиентов системы управления автомойками
    description: API description
    version: 1.0

    contact:
      email: support@carwashservice.online
      url: https://carwashservice.online
      name: Zagidulin Nail

  swagger-ui:
    path: /swagger-ui.html

---
spring:
  profiles: test
  application:
    name: carwash-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/carwashes_test
      repositories:
        enabled: true

server:
  port: 8085